# Generated by Django 3.0.7 on 2020-07-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.TextField(max_length=100)),
                ('institute', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('grade', models.TextField(max_length=5)),
                ('graduation', models.TextField(max_length=4)),
            ],
        ),
    ]
