# Generated by Django 3.0.7 on 2020-07-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(max_length=100)),
                ('type', models.TextField(max_length=100)),
                ('period', models.TextField(max_length=100)),
                ('location', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('at', models.TextField(max_length=100)),
                ('period', models.TextField(max_length=100)),
                ('role', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.TextField(max_length=100)),
                ('role', models.TextField(max_length=100)),
                ('reason', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
