# Generated by Django 3.0.7 on 2020-07-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200731_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='grade',
            field=models.TextField(max_length=50),
        ),
    ]
