# Generated by Django 3.0.7 on 2020-07-31 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_auto_20200731_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.TextField(default='comapy', max_length=100),
            preserve_default=False,
        ),
    ]
