# Generated by Django 3.0.7 on 2020-08-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
