# Generated by Django 3.0.7 on 2020-08-08 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_auto_20200804_1133'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
